# Generated by Django 4.2.5 on 2023-12-18 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("origin", models.CharField(max_length=64, verbose_name="Пункт відправлення")),
                ("destination", models.CharField(max_length=64, verbose_name="Пункт призначення")),
                ("price", models.PositiveIntegerField(default=50, verbose_name="Ціна(грн)")),
                ("is_paid", models.BooleanField(default=False, verbose_name="Оплачено")),
                ("scheduled_time", models.TimeField(verbose_name="Запланований час поїздки")),
                ("scheduled_date", models.DateField(verbose_name="Запланована дата поїздки")),
                ("date_created", models.DateTimeField(auto_now_add=True, verbose_name="Дата створення")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Користувач",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поїздка",
                "verbose_name_plural": "Поїздки",
            },
        ),
    ]
