name: Django CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        pip install --upgrade pip pipenv setuptools
    - name: Run Tests
      run: |
        pipenv lock
        pipenv sync --system
        python manage.py test
        pre-commit install
        pre-commit run
